### ISSUE TITLE
Setup Kind custers before running the integration tests

### ISSUE THREAD

**Issue by razvan** [stackabletech/integration-tests#18]
To automate the integration tests as much as possible, a script should be created that:

- Creates a fresh kind cluster using a  definition file that is expected in each operator repo (see dev-cluster.yml in the Druid operator repo for an example)
- Set up the operator requirements (using helm?)
- Run the tests.

Tested with the following operators:

- [x] druid
- [x] hive
- [x] kafka
- [x] nifi
- [x] opa 
- [x] spark
- [x] superset
- [x] trino (*)
- [x] zookeeper

(*) The Trino integration tests don't work on Ubuntu 20.04 LTS because of certificate issues, but they do work in T2.

**Comment by lfrancke** [comment]
I'm uncertain how much overlap there is between this one and https://github.com/stackabletech/issues/issues/137

@maltesander and @razvan to coordinate and decide how to proceed.
