### ISSUE TITLE
Spark k8s Tests

### ISSUE THREAD

**Issue by fhennig** [stackabletech/integration-tests#199]
We want to add kuttl tests for our new operator https://github.com/stackabletech/spark-k8s-operator

The operator repo contains example yamls for jobs that can be used as a base.

We have a couple of test cases so far:
- a python job supplied in an image
- a python job supplied from s3 (should be done with MinIO)
- a java job supplied in an image: The SparkPi job. This includes the data in the image as well.

**Comment by lfrancke** [comment]
You could also talk to @snocke about this as he's writing a Spark job to access HBase, might be helpful, might not be.
