### ISSUE TITLE
Open KEP with Kuttl project to discuss whether parameterized tests make sense

### ISSUE THREAD

**Issue by soenkeliebau** [stackabletech/integration-tests#206]
opened for @lfrancke

**Comment by soenkeliebau** [comment]
I was bored on the train and opened https://github.com/kudobuilder/kuttl/issues/350 to gauge whether there is an appetite for functionality like this before going through the hassle of writing a KEP

**Comment by soenkeliebau** [comment]
Had a brief discussion here: https://kubernetes.slack.com/archives/CG3HTFCMV/p1649681144207229

Quick summary:

- like to see patching used rather than templating
- afraid that building a test matrix is tough to validate because it needs to be flexible on the schema/definition side by intention

**Comment by lfrancke** [comment]
Is it worth linking to that discussion in the upstream issue as well?

**Comment by soenkeliebau** [comment]
done

**Comment by lfrancke** [comment]
I talked to Sönke and we believe that we are now at a point where we can open the KEP as the next step.

As Sönke mentioned earlier there are two proposals: patching vs. templating.
We would prefer a templating approach.

**Comment by fhennig** [comment]
There is a new PR that mentions our ticket: https://github.com/kudobuilder/kuttl/pull/387

**Comment by razvan** [comment]
As discussed in today's daily, we are closing this ticket. Our focus is now on improving the stability of the integration tests and one strategy might be to remove `kuttl` completely from the CI pipeline.
