### ISSUE TITLE
Add test case to run the operators in a non-default namespace

### ISSUE THREAD

**Issue by soenkeliebau** [stackabletech/integration-tests#48]
As seen in https://github.com/stackabletech/zookeeper-operator/issues/297 we currently have trouble when the operator is running in a separate namespace. 
We should test this for all operators in the integration tests.

**Comment by lfrancke** [comment]
Can we change the integration tests to generate & use a random name for each run?

**Comment by maltesander** [comment]
Name or namespace? KUTTL automatically generates random namespaces for each run, the name of the resources is fixed.

**Comment by lfrancke** [comment]
Namespace, sorry.

Okay, that's great then! This means we can close this meeting when everything is in kuttl?

**Comment by lfrancke** [comment]
I'm going to move this to the backlog so a dev can look at it and decide whether this can be closed or not.
